category: EDUCATION_AND_REFERENCE
defaultLocale: fr
localizedSettings:
  developerEmail: dev.edrlab@gmail.com
  developerName: edrlab
  displayName: dev edrlab
  fullDescription: lis mon live edrlab demo
  privacyPolicyUrl: https://www.edrlab.org/lml-privacy-policy/
  pronunciation: dev edrlab
  sampleInvocations:
  - Parler avec edrlab
  - Connecter avec edrlab
  - Discuter avec edrlab
  shortDescription: lis mon livre
  smallLogoImage: https://lh3.googleusercontent.com/IPE84cRJZSbgpkLCNMhJFkP_sbh5e18cYRvn30hVHE6nYNLfQ_9a-opqTKbQNThVPUzo8sfP1_cR
  voice: female_1
projectId: edrlab-1
