accountLinking:
  appClientId: "123456"
  authGrantType: IMPLICIT
  authorizationUrl: https://opds-auth-test-server-aplqpqv3wa-ey.a.run.app/implicit/login
  linkingType: OAUTH
category: EDUCATION_AND_REFERENCE
defaultLocale: fr
localizedSettings:
  displayName: edrlab
  pronunciation: edrlab
  voice: female_1
projectId: cela-2
testingInstructions: |-
  admin
  admin
