/* eslint-disable */
// DO NOT EDIT! This file is generated with "typed-18next" tool.

export interface Translations {
    keys: {
        "fr": "error.bearerTokenNotDefined" | "error.catch" | "error.convadd" | "error.urlNotValid" | "error.noQuery" | "error.webpubNotDefined" | "error.selectionListNotDefined" | "error.selectionPubNotDefined" | "error.selectionNotAvailable" | "main.welcome" | "home.information" | "home.welcome" | "homeMembers.welcome1" | "homeMembers.welcome2" | "homeMembers.resumeAudiobook.noCurrentListening" | "homeMembers.selection.welcome" | "homeMembers.selection.publication" | "homeMembers.selection.listAfterSelection" | "homeMembers.list.wrongNumber" | "homeMembers.list.numberPublication" | "homeMembers.list.numberSelection" | "homeMembers.list.numero" | "homeMembers.list.numeroWithAuthor" | "homeMembers.list.numeroWithAuthorOf" | "homeMembers.list.noResult" | "homeMembers.search" | "player.askResumeLastOffset" | "player.mediaStatus.notCorrect" | "player.remaining.hoursAndMinute" | "player.remaining.minute" | "test.player" | "test.setupSdk" | "test.webhook" | "free"
    };
    keysWithNS: {
        "fr": "fr:error.bearerTokenNotDefined" | "fr:error.catch" | "fr:error.convadd" | "fr:error.urlNotValid" | "fr:error.noQuery" | "fr:error.webpubNotDefined" | "fr:error.selectionListNotDefined" | "fr:error.selectionPubNotDefined" | "fr:error.selectionNotAvailable" | "fr:main.welcome" | "fr:home.information" | "fr:home.welcome" | "fr:homeMembers.welcome1" | "fr:homeMembers.welcome2" | "fr:homeMembers.resumeAudiobook.noCurrentListening" | "fr:homeMembers.selection.welcome" | "fr:homeMembers.selection.publication" | "fr:homeMembers.selection.listAfterSelection" | "fr:homeMembers.list.wrongNumber" | "fr:homeMembers.list.numberPublication" | "fr:homeMembers.list.numberSelection" | "fr:homeMembers.list.numero" | "fr:homeMembers.list.numeroWithAuthor" | "fr:homeMembers.list.numeroWithAuthorOf" | "fr:homeMembers.list.noResult" | "fr:homeMembers.search" | "fr:player.askResumeLastOffset" | "fr:player.mediaStatus.notCorrect" | "fr:player.remaining.hoursAndMinute" | "fr:player.remaining.minute" | "fr:test.player" | "fr:test.setupSdk" | "fr:test.webhook" | "fr:free"
    };
}
