/* eslint-disable */
// DO NOT EDIT! This file is generated with "typed-18next" tool.

export interface Translations {
    keys: {
        "en": "main.welcome.noLinked.1" | "main.welcome.linked.1" | "home_new_user.enter.first.1" | "home_new_user.enter.first.2" | "home_new_user.no.1" | "home_new_user.no.2" | "home_new_user.help.1" | "home_new_user.help.2" | "home_new_user.maybeLater.1" | "home_new_user.maybeLater.2" | "home_new_user_maybe_later.help.1" | "home_new_user_no.help.1" | "info.about.1" | "info.help.1" | "info.yesOrMembership.1" | "home_user.enter.newlyUser.1" | "home_user.enter.newlyUser.2" | "home_user.enter.playing.1" | "home_user.enter.playing.2" | "home_user.enter.playing.3" | "home_user.enter.regular.1" | "home_user.help.1" | "home_user.help.2" | "search.enter.1" | "selection.enter.bookshelf.first" | "selection.enter.bookshelf.second" | "selection.enter.search" | "selection.enter.collection.publication" | "selection.enter.collection.group" | "selection.enter.lastPage.publication" | "selection.enter.lastPage.group" | "selection.enter.lastPage.notAvailable" | "selection.enter.common.1" | "selection.enter.common.2" | "selection.enter.common.3" | "selection.enter.empty.1" | "selection.help.1" | "selection.help.2" | "player.start" | "collections.enter.1" | "collections.help.1" | "void" | "bye.1" | "fallback.1" | "fallback.2" | "silence.1" | "silence.2" | "error.1",
        "fr": "error.bearerTokenNotDefined" | "error.catch" | "error.convadd" | "error.urlNotValid" | "error.noQuery" | "error.webpubNotDefined" | "error.selectionListNotDefined" | "error.selectionPubNotDefined" | "error.selectionNotAvailable" | "main.welcome" | "home.information" | "home.welcome" | "homeMembers.welcome1" | "homeMembers.welcome2" | "homeMembers.resumeAudiobook.noCurrentListening" | "homeMembers.selection.welcome" | "homeMembers.selection.publication" | "homeMembers.selection.next" | "homeMembers.selection.noNext" | "homeMembers.selection.listAfterSelection" | "homeMembers.list.wrongNumber" | "homeMembers.list.numberSelection" | "homeMembers.list.numberPublication" | "homeMembers.list.pagePublication" | "homeMembers.list.numero" | "homeMembers.list.numeroWithAuthor" | "homeMembers.list.numeroWithAuthorOf" | "homeMembers.list.noResult" | "homeMembers.list.repeat" | "homeMembers.search" | "player.start" | "player.askResumeLastOffset" | "player.mediaStatus.notCorrect" | "player.remaining.hoursAndMinute" | "player.remaining.minute" | "player.toc.notFound" | "player.toc.numero" | "player.toc.noNext" | "player.notAvailable" | "test.player" | "test.setupSdk" | "test.webhook" | "free"
    };
    keysWithNS: {
        "en": "en:main.welcome.noLinked.1" | "en:main.welcome.linked.1" | "en:home_new_user.enter.first.1" | "en:home_new_user.enter.first.2" | "en:home_new_user.no.1" | "en:home_new_user.no.2" | "en:home_new_user.help.1" | "en:home_new_user.help.2" | "en:home_new_user.maybeLater.1" | "en:home_new_user.maybeLater.2" | "en:home_new_user_maybe_later.help.1" | "en:home_new_user_no.help.1" | "en:info.about.1" | "en:info.help.1" | "en:info.yesOrMembership.1" | "en:home_user.enter.newlyUser.1" | "en:home_user.enter.newlyUser.2" | "en:home_user.enter.playing.1" | "en:home_user.enter.playing.2" | "en:home_user.enter.playing.3" | "en:home_user.enter.regular.1" | "en:home_user.help.1" | "en:home_user.help.2" | "en:search.enter.1" | "en:selection.enter.bookshelf.first" | "en:selection.enter.bookshelf.second" | "en:selection.enter.search" | "en:selection.enter.collection.publication" | "en:selection.enter.collection.group" | "en:selection.enter.lastPage.publication" | "en:selection.enter.lastPage.group" | "en:selection.enter.lastPage.notAvailable" | "en:selection.enter.common.1" | "en:selection.enter.common.2" | "en:selection.enter.common.3" | "en:selection.enter.empty.1" | "en:selection.help.1" | "en:selection.help.2" | "en:player.start" | "en:collections.enter.1" | "en:collections.help.1" | "en:void" | "en:bye.1" | "en:fallback.1" | "en:fallback.2" | "en:silence.1" | "en:silence.2" | "en:error.1",
        "fr": "fr:error.bearerTokenNotDefined" | "fr:error.catch" | "fr:error.convadd" | "fr:error.urlNotValid" | "fr:error.noQuery" | "fr:error.webpubNotDefined" | "fr:error.selectionListNotDefined" | "fr:error.selectionPubNotDefined" | "fr:error.selectionNotAvailable" | "fr:main.welcome" | "fr:home.information" | "fr:home.welcome" | "fr:homeMembers.welcome1" | "fr:homeMembers.welcome2" | "fr:homeMembers.resumeAudiobook.noCurrentListening" | "fr:homeMembers.selection.welcome" | "fr:homeMembers.selection.publication" | "fr:homeMembers.selection.next" | "fr:homeMembers.selection.noNext" | "fr:homeMembers.selection.listAfterSelection" | "fr:homeMembers.list.wrongNumber" | "fr:homeMembers.list.numberSelection" | "fr:homeMembers.list.numberPublication" | "fr:homeMembers.list.pagePublication" | "fr:homeMembers.list.numero" | "fr:homeMembers.list.numeroWithAuthor" | "fr:homeMembers.list.numeroWithAuthorOf" | "fr:homeMembers.list.noResult" | "fr:homeMembers.list.repeat" | "fr:homeMembers.search" | "fr:player.start" | "fr:player.askResumeLastOffset" | "fr:player.mediaStatus.notCorrect" | "fr:player.remaining.hoursAndMinute" | "fr:player.remaining.minute" | "fr:player.toc.notFound" | "fr:player.toc.numero" | "fr:player.toc.noNext" | "fr:player.notAvailable" | "fr:test.player" | "fr:test.setupSdk" | "fr:test.webhook" | "fr:free"
    };
}
