
name: sdk test dev

on:
  push:
    branches: [ develop ]
    #    paths:
    #  pull_request:
    #   branches: [ develop ]
    paths:
      - 'sdk/test/**'
      - 'test/dev/**'
      - '.github/workflows/sdk-test-dev.yml'

jobs:
  sdk-test-dev:
    name: "Test sdk DEV"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    defaults:
      run:
        working-directory: './test/dev'

    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: save service_account
        run: echo $SECRET >> service_account.json
        env:
          SECRET : ${{ secrets.SERVICE_ACCOUNT_VALENTIN5 }}
      - run: npm install
      - run: npm test
